var modo=modo||{},console,$j=jQuery.noConflict(),translated_text=[],EMAIL_REGEX=/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i,USERNAME_REGEX=/^[a-zA-Z0-9][a-zA-Z0-9_-]+[a-zA-Z0-9]$/,SUBDOMAIN_REGEX=/^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$/,US_PHONE_NUMBER_REGEX=
/^\d{10}$/,PHONE_NUMBER_REGEX=/^(\d)+$/,SCRIPT_TAGS_REGEX=/<script[^>]*>.*?<\/script>/i,LINK_REGEX=/^(https?:\/\/)?[^<^>]+/,URL_REGEX=/^(ftp|https?):\/\/+(www\.)?[a-z0-9\-\.]{3,}\.[a-z]{3}$/,WWW_REGEX=/^(www.)[a-z0-9\-\.]{3,}\.[a-z]{3}$/,AJAX_ANALYTICS=1,IS_IPAD=navigator.userAgent.match(/iPad/i)!=null;function parentQuizResults(a){goAjax("/message/ajax-parent-quiz-results",{quiz_run_id:a},function(c){displayParentQuizResults(c,a)})}
function displayParentQuizResults(a,c){var b=eval("("+a+")");if(b.multi_student){var d="";if(b.scores.length>0){d='<div class="student-quiz-results">';for(si in b.scores){d+='<div class="student-result">';d+='<img src="'+b.scores[si].thumb+'" />';d+='<h3><a href="/quiz/result/quiz_run_id/'+c+"/user_id/"+b.scores[si].user_id+'">'+b.scores[si].name+"</a></h3>";if(b.scores[si].status!="FINISHED"&&b.scores[si].status!="GRADED")d+="<p>Not taken, yet</p>";else if(b.scores[si].show_results){var e=b.scores[si].num_questions-
b.scores[si].num_graded_questions,f="";if(e)f="("+e+" "+translated_text.ungraded+")";d+="<p><strong>"+(b.scores[si].score+"/"+b.scores[si].total_points)+"</strong>"+f+"</p>"}else d+="<p>Results currently hidden by instructor</p>";d+="</div>"}}else{d='<div class="student-quiz-results">';d+='<div class="student-result">';d+='<p class="none-submitted">No students have taken the quiz yet.</p>';d+="</div>"}d+="</div>";$j.facebox(d);$j.facebox.setTitle(translated_text["view-submission"])}else window.location.href=
"/quiz/result/quiz_run_id/"+c+"/user_id/"+b.student_ids[0]}
modo.resources={showEmbed:function(a,c,b,d,e,f){b=b||$j(".embed-frame-"+a).val();e=e||"";b.search("EDMODO_EMBED_PLAY_KEY")!=-1?goAjax("/embed/ajax-generate-key",{embed_id:a},function(g){modo.resources.displayEmbed(a,c,b,d,g)}):modo.resources.displayEmbed(a,c,b,d,0,e,f)},isInlineEmbed:function(a){var c=true,b=a.split('width="');if(typeof b[1]!="undefined"){b[1]=b[1].replace("px","");b=b[1].split('"');if(b[0]>515)c=false}else{b=a.split("width='");if(typeof b[1]!="undefined"){b[1]=b[1].replace("px",
"");b=b[1].split("'");if(b[0]>515)c=false}}if(c){a=a.split("width:");if(typeof a[1]!="undefined"){a[1]=a[1].replace("px","");a[1]=$j.trim(a[1]);b=a[1].split(";");if(b[0]>515)c=false}}return c},displayEmbed:function(a,c,b,d,e,f,g){f=f||"";if(e)b=b.replace("EDMODO_EMBED_PLAY_KEY",e);!b&&c?$j("#embeded-code-"+c+" #embed-content-"+a).html(""):$j("#embed-content-"+a).html("");if(!modo.resources.isInlineEmbed(b)||d){if(f=="")if($j("#embed-title-"+a).length>0)f=$j("#embed-title-"+a).html();else if($j(".ResourcesInfoPanel.embed .header-wrap div").length>
0)f=$j(".ResourcesInfoPanel.embed .header-wrap div").html();else if($j("#resource_item_"+a+" a.title").length>0)f=$j("#resource_item_"+a+" a.title").html();$j.facebox(b);$j.facebox.setTitle(f)}else if(c){$j("#embeded-code-"+c+" #embed-title-"+a).unbind("click");$j("#embeded-code-"+c+" #embed-content-"+a).html(b)}else{$j("#embed-title-"+a).unbind("click");$j("#embed-content-"+a).html(b)}g||goAjax("/message/ajax-log-embed-view",{embed_id:a,message_id:c})}};
modo.apps={toggleLaunchpad:function(){if($j("#app-launchpad").hasClass("active")){$j("#app-launchpad").removeClass("active");$j("#apps").hide();$j("#nav").css("border-bottom","2px solid #eee");if($j("#app-canvas").css("display")!="block"){$j("#content").show();$j("#footer").show()}}else{$j("#app-launchpad").addClass("active");$j("#content").hide();$j("#footer").hide();$j("#nav").css("border-bottom","none");$j("#apps").css("height",$j(window).height());$j(window).resize(function(){$j("#apps").css("height",
$j(window).height())});goAjax("/apps/menu",{},function(a){$j("#apps div").html(a)});$j("#apps").show()}},launchApp:function(a){$j.getJSON("/home/ajax-launch-app",{app_id:a},function(c){modo.apps.loadApp(c)})},loadApp:function(a){$j("#app-canvas").empty();$j("#app-canvas").html('<iframe src="'+a.app_url+'" scrollbar="no" frameborder="0"></iframe>');modo.apps.toggleLaunchpad();$j("#content").hide();$j("#footer").hide();$j("body").css("overflow-y","hidden");$j("html").css("overflow-y","hidden");$j("#app-canvas iframe").css("height",
$j(window).height()-38);$j(window).resize(function(){$j("#app-canvas iframe").css("height",$j(window).height()-38)});$j("#app-canvas").show()}};
modo.badges={sharedBadgeBox:function(a){$j.getJSON("/badge/ajax-shared-badge-box",{format:"xhtml",viewed_user:a},function(c){modo.badges.loadSharedBadgeBox(c,a)})},loadSharedBadgeBox:function(a,c){if(!($j("#facebox .shared-badge-box").length>0)){$j.facebox($j("#shared-badge-box-wrap").html());$j.facebox.setTitle("Shared Badges")}$j("#facebox .selected-badge").html("");$j("#facebox .viewed-user").html(c);$j("#facebox .shared-badge-box .badge-list").html(utf8Decode(a.badge_list));$j("#facebox .shared-badge-box .badge-panel-selected").html(utf8Decode(a.badge_panel));
$j("#facebox .shared-badge-box .badge-panel-selected").show();$j("#facebox .badge-full-view-panel").hide();$j("#facebox .shared-badge-box .badge-list").show();$j("#facebox .shared-badge-box .badge-panel").show()},badgeBox:function(a,c,b){$j.getJSON("/badge/ajax-badge-box",{format:"xhtml",viewed_user:a,awarded_by:c},function(d){modo.badges.loadBadgeBox(d,a,b)})},loadBadgeBox:function(a,c,b){if(!($j("#facebox .badge-box").length>0)){$j.facebox($j("#badge-box-wrap").html());$j.facebox.setTitle("Badges")}$j("#facebox .remove-badge-button").hide();
$j("#facebox .already-awarded").hide();$j("#facebox .edit-badge-panel").hide();$j("#facebox .shared-badge-panel").hide();$j("#facebox .badge-full-view-panel").hide();$j("#facebox .awarded-by-panel").hide();$j("#facebox .selected-badge").html("");$j("#facebox .viewed-user").html(c);$j("#facebox .badge-box .badge-list").html(utf8Decode(a.badge_list));$j("#facebox .badge-box .badge-list").show();$j("#facebox .badge-box .badge-panel").show();$j("#facebox .badge-full-other-users-toggle").hasClass("expanded")&&
modo.badges.toggleOtherUsersListSize();if(b!=0)modo.badges.selectAwardBadgeBox(b);else{$j("#facebox .badge-box .badge-panel-selected").html(utf8Decode(a.badge_panel));$j("#facebox .badge-box .badge-panel-selected").show()}},filterBadgeBox:function(a,c){$j.each($j("#facebox .nav-badge-creators a"),function(){$j(this).removeClass("current")});a!=0?$j("#facebox .nav-badge-creators .teacher-"+a).addClass("current"):$j("#facebox .nav-badge-creators .all-badges").addClass("current");$j.getJSON("/badge/ajax-badge-box",
{format:"xhtml",viewed_user:c,awarded_by:a},function(b){modo.badges.loadBadgeBox(b,c,0)})},awardBadgeBox:function(a){$j.getJSON("/badge/ajax-award-badge-box",{format:"xhtml",viewed_user:a},function(c){modo.badges.loadAwardBadgeBox(c,a,0)})},loadAwardBadgeBox:function(a,c,b){if(!($j("#facebox .award-badge-box").length>0)){$j.facebox($j("#award-badge-box-wrap").html());c!=0?$j.facebox.setTitle("Award Badge"):$j.facebox.setTitle("My Student Badges")}$j("#facebox .award-badge-button").hide();$j("#facebox .badge-added").hide();
$j("#facebox .already-awarded").hide();$j("#facebox .edit-badge-panel").hide();$j("#facebox .shared-badge-panel").hide();$j("#facebox .badge-full-view-panel").hide();$j("#facebox .awarded-by-panel").hide();$j("#facebox .new-badge-form").hide();$j("#facebox .edit-badge-form").hide();$j("#facebox .badge-panel").show();$j("#facebox .badge-list").show();$j("#facebox .selected-badge").html("");$j("#facebox .viewed-user").html(c);$j("#facebox .award-badge-box .badge-list").html(utf8Decode(a.badge_list));
$j("#facebox .badge-full-other-users-toggle").hasClass("expanded")&&modo.badges.toggleOtherUsersListSize();b!=0?modo.badges.selectAwardBadgeBox(b):$j("#facebox .award-badge-box .badge-panel-selected").html(utf8Decode(a.badge_panel));modo.badges.clearAwardBadgeBoxForms()},clearAwardBadgeBoxForms:function(){typeof modo.badges.edit_image_uploader!="undefined"&&modo.badges.edit_image_uploader.reset();$j("#facebox .edit-badge-title").val("");$j("#facebox .edit-badge-description").val("");typeof modo.badges.image_uploader!=
"undefined"&&modo.badges.image_uploader.reset();$j("#facebox .new-badge-title").val("");$j("#facebox .new-badge-description").val("");$j("#facebox .new-badge-shared-check").attr("checked","checked");$j("#facebox .edit-badge-shared-check").removeAttr("checked");$j("#facebox .edit-badge-delete").show();$j("#facebox .delete-badge-confirm").hide();$j("#facebox .delete-badge-yes").show();$j("#facebox .delete-badge-no").show();$j("#facebox .delete-badge-loading").hide()},selectAwardBadgeBox:function(a){modo.badges.deselectAwardBadgeBox();
$j("#facebox .badge-in-list.badge-"+a).addClass("selected");modo.badges.loadPanelAwardBadgeBox(a)},showAndSelectAwardBadgeBox:function(a,c){modo.badges.filterAwardBadgeBox("created_by_me",c,a)},deselectAwardBadgeBox:function(){$j("#facebox .badge-in-list").removeClass("selected")},loadPanelAwardBadgeBox:function(a){$j("#facebox .badge-panel-selected").html($j("#facebox .badge-in-list.badge-"+a).html());$j("#facebox .badge-panel-selected p.description").show();$j("#facebox .badge-panel-selected").prepend('<a onclick="modo.badges.viewFullBadge('+
a+')" class="view-full-badge"><span>Badge Details</span></a>');$j("#facebox .badge-added").hide();$j("#facebox .award-badge-button").show();$j("#facebox .selected-badge").html(a);$j("#facebox .already-awarded").html($j("#facebox .badge-panel-selected .already-earned").html());$j("#facebox .already-awarded").show();$j("#facebox .edit-badge-panel").html($j("#facebox .badge-panel-selected .edit-badge").html());$j("#facebox .edit-badge-panel").show();$j("#facebox .add-badge-button").show();if($j("#facebox .badge-panel-selected .share-badge").html()==
"1"){$j("#facebox .shared-badge-panel").html("Shared");$j("#facebox .shared-badge-panel").show()}else{$j("#facebox .shared-badge-panel").html();$j("#facebox .shared-badge-panel").hide()}$j("#facebox .already-awarded").html($j("#facebox .badge-panel-selected .already-earned").html());if($j("#facebox .awarded-by-panel").length>0){$j("#facebox .awarded-by-panel").html($j("#facebox .badge-panel-selected .awarded-by").html());$j("#facebox .awarded-by-panel").show()}},revokeBadge:function(){var a=$j("#facebox .viewed-user").html(),
c=$j("#facebox .selected-badge").html();$j("#facebox .revoke-badge").html("Revoking, please wait...");$j("#facebox .revoke-badge").css("color","#999");$j("#facebox .revoke-badge").css("cursor","default");goAjax("/badge/ajax-revoke-badge",{viewed_user:a,badge_id:c},modo.badges.afterRevokeBadge)},afterRevokeBadge:function(){window.location.reload()},awardBadge:function(){var a=$j("#facebox .viewed-user").html(),c=$j("#facebox .selected-badge").html();if(a.search("-")==-1){if($j("#member-badges-"+a).length>
0){var b=0;b=$j("#member-badges-"+a).html();b++;$j("#member-badges-"+a).html(b);$j("#member-badges-"+a).show()}}else{var d=a.split("-");for(i in d)if(d[i]!=""){b=$j("#member-badges-"+d[i]).html();b++;$j("#member-badges-"+d[i]).html(b);$j("#member-badges-"+d[i]).show()}}goAjax("/badge/ajax-award-badge",{viewed_user:a,badge_id:c},modo.badges.afterAwardBadge)},afterAwardBadge:function(a){$j.facebox.close();var c=0;c=$j("#see-all-badges span").html();c++;$j("#see-all-badges span").html(c);c==1?$j("#see-all-badges strong").html("Badge Earned"):
$j("#see-all-badges strong").html("Badges Earned");if($j("#badge-wrap").length>0){if(c>7){var b=1;$j.each($j("#badge-wrap a"),function(){b>6&&$j(this).hide();b++})}$j("#badge-wrap").prepend(a)}var d=false;$j.each($j("#badge-wrap .badge-ribbon-mystery"),function(){if($j(this).css("display")=="block"&&!d){$j(this).hide();d=true}});$j("#see-all-badges").show();$j("#no-badges").hide();$j(".success.notify-bar.badge-awarded").show();setTimeout(function(){$j(".success.notify-bar.badge-awarded").fadeOut()},
7E3)},addBadge:function(){var a=$j("#facebox .selected-badge").html();goAjax("/badge/ajax-add-badge",{badge_id:a},modo.badges.afterAddBadge)},afterAddBadge:function(){$j("#facebox .award-badge-button").hide();$j("#facebox .badge-added").show()},filterAwardBadgeBox:function(a,c,b){$j("#facebox .nav-badge-creators .badges-by-me").removeClass("current");$j("#facebox .nav-badge-creators .new-badge").removeClass("current");$j("#facebox .nav-badge-creators .badges-by-edmodo").removeClass("current");if(a==
"created_by_me"){$j("#facebox .nav-badge-creators .badges-by-me").addClass("current");$j.getJSON("/badge/ajax-award-badge-box",{format:"xhtml",viewed_user:c},function(e){modo.badges.loadAwardBadgeBox(e,$j("#facebox .viewed-user").html(),b)})}else if(a=="by_edmodo"){$j("#facebox .nav-badge-creators .badges-by-edmodo").addClass("current");$j.getJSON("/badge/ajax-award-badge-box",{format:"xhtml",viewed_user:c,by_edmodo:1},function(e){modo.badges.loadAwardBadgeBox(e,$j("#facebox .viewed-user").html(),
0)})}else if(a=="new_badge"){$j("#facebox .nav-badge-creators .new-badge").addClass("current");$j("#facebox .badge-list").hide();$j("#facebox .badge-panel").hide();$j("#facebox .edit-badge-form").hide();$j("#facebox .new-badge-form").show();$j("#facebox .badge-full-view-panel").hide();$j("#facebox .badge-full-other-users-toggle").hasClass("expanded")&&modo.badges.toggleOtherUsersListSize();if($j("#facebox .new-badge-image-wrap .ImageUploader").length==0){var d=modo.badges.image_uploader=new ImageUploader("/badge/ajax-send-badge-image",
0);$j("#facebox .new-badge-image-wrap").append(d.jq);GlobalDispatcher_j.bind(ImageUploader.IMAGE_UPLOADED,function(e,f){d.setThumb(f);d.reset_j.show();$j("#facebox .new-badge-image-url").html(f)})}}},viewFullBadge:function(a){$j.getJSON("/badge/ajax-badge-full-view",{badge_id:a,viewed_user:$j("#facebox .viewed-user").html()},function(c){modo.badges.showBadgeFullView(c)})},toggleOtherUsersListSize:function(){if($j("#facebox .badge-full-other-users-toggle").hasClass("expanded")){$j("#facebox .badge-full-other-users-toggle").removeClass("expanded");
$j("#facebox .badge-full-other-users-toggle").html("Expand List");$j("#facebox .badge-full-other-users-toggle").css("background-image",'url("/images/blue-up-tri.png")');$j("#facebox .badge-full-other-users h3").css("margin-top","10px");$j("#facebox .badge-full-view-panel .badge-earners-wrap").css("height","125px");$j("#facebox .badge-full-close").show();$j("#facebox .badge-full-image").show();$j("#facebox .badge-full-title").show();$j("#facebox .badge-full-description").show()}else{$j("#facebox .badge-full-other-users-toggle").addClass("expanded");
$j("#facebox .badge-full-close").hide();$j("#facebox .badge-full-image").hide();$j("#facebox .badge-full-title").hide();$j("#facebox .badge-full-description").hide();$j("#facebox .badge-full-other-users h3").css("margin-top","0");$j("#facebox .badge-full-view-panel .badge-earners-wrap").css("height","380px");$j("#facebox .badge-full-other-users-toggle").html("Collapse List");$j("#facebox .badge-full-other-users-toggle").css("background-image",'url("/images/icons/downarrow.gif")')}},showBadgeFullView:function(a){$j("#facebox .nav-badge-creators .badges-by-me").removeClass("current");
$j("#facebox .nav-badge-creators .new-badge").removeClass("current");$j("#facebox .nav-badge-creators .badges-by-edmodo").removeClass("current");$j.each($j("#facebox .nav-badge-creators a"),function(){$j(this).removeClass("current")});$j("#facebox .badge-list").hide();$j("#facebox .badge-panel").hide();$j("#facebox .edit-badge-form").hide();$j("#facebox .new-badge-form").hide();$j("#facebox .shared-badge-box .award-badge-button").hide();$j("#facebox .badge-full-view-panel .badge-full-image").html(a.image);
$j("#facebox .badge-full-view-panel .badge-full-image").removeClass("has-large");a.has_large&&$j("#facebox .badge-full-view-panel .badge-full-image").addClass("has-large");$j("#facebox .badge-full-view-panel .badge-full-title").html(a.title);if(a.description=="")a.description="<em>No description...</em>";$j("#facebox .badge-full-view-panel .badge-full-description").html("<h3>Description</h3><p>"+a.description+"</p>");$j("#facebox .badge-full-view-panel .badge-full-other-users").html("");var c="";
if(a.other_users.length>0)c='<a onclick="modo.badges.toggleOtherUsersListSize();" class="badge-full-other-users-toggle">Expand List</a>';a.classmates?$j("#facebox .badge-full-view-panel .badge-full-other-users").html("<h3>"+c+"Classmates that have also earned <strong>"+a.title+"</strong></h3>"):$j("#facebox .badge-full-view-panel .badge-full-other-users").html("<h3>"+c+"Students that have earned <strong>"+a.title+"</strong></h3>");if(a.other_users.length>0){c="";for(i in a.other_users){var b=a.other_users[i];
c+='<div class="badge-earner"><div class="earner-avatar"><a href="/user?uid='+b.user_id+'"><img src="'+b.thumb+'" /></a></div><div class="earner-name">'+b.name+"</div></div>"}$j("#facebox .badge-full-view-panel .badge-full-other-users").append('<div class="badge-earners-wrap">'+c+"</div>")}else a.classmates?$j("#facebox .badge-full-view-panel .badge-full-other-users").append("<p><em>None of your classmates have earned this badge, yet.</em></p>"):$j("#facebox .badge-full-view-panel .badge-full-other-users").append("<p><em>No students have earned this badge, yet.</em></p>");
$j("#facebox .badge-full-view-panel").show()},editBadge:function(a){$j("#facebox .nav-badge-creators .badges-by-me").removeClass("current");$j("#facebox .nav-badge-creators .new-badge").removeClass("current");$j("#facebox .nav-badge-creators .badges-by-edmodo").removeClass("current");$j("#facebox .badge-list").hide();$j("#facebox .badge-panel").hide();$j("#facebox .new-badge-form").hide();$j("#facebox .edit-badge-form").show();var c=$j("#facebox .badge-in-list.badge-"+a+" span").html(),b=$j("#facebox .badge-in-list.badge-"+
a+" .description").html(),d=$j("#facebox .badge-in-list.badge-"+a+" .share-badge").html(),e=$j("#facebox .badge-in-list.badge-"+a+" .badge-border").css("background-image");e=e.replace('url("',"");e=e.replace('")',"");e=e.replace("url(","");e=e.replace(")","");$j("#facebox .edit-badge-form .edit-badge-title").val(c);$j("#facebox .edit-badge-form .edit-badge-description").val(b);d=="1"?$j("#facebox .edit-badge-form .edit-badge-shared-check").attr("checked","checked"):$j("#facebox .edit-badge-form .edit-badge-shared-check").removeAttr("checked");
$j("#facebox .edit-badge-image-url").html(e);$j("#facebox .edit-badge-id").html(a);if($j("#facebox .edit-badge-image-wrap .ImageUploader").length==0){var f=modo.badges.edit_image_uploader=new ImageUploader("/badge/ajax-send-badge-image",0);f.setThumb(e);$j("#facebox .edit-badge-image-wrap").append(f.jq);GlobalDispatcher_j.bind(ImageUploader.IMAGE_UPLOADED,function(g,h){f.setThumb(h);f.reset_j.show();$j("#facebox .edit-badge-image-url").html(h)})}else modo.badges.edit_image_uploader.setThumb(e)},createBadge:function(){var a=
$j("#facebox .new-badge-title").val(),c=$j("#facebox .new-badge-description").val(),b=$j("#facebox .new-badge-image-url").html(),d="1";if($j("#facebox .new-badge-shared-check").attr("checked")==false)d="0";var e=true;if(a==""){e=false;$j("#facebox .new-badge-title").addClass("error")}else $j("#facebox .new-badge-title").removeClass("error");if(b==""){e=false;$j("#facebox .new-badge-image-wrap").addClass("error")}else $j("#facebox .new-badge-image-wrap").removeClass("error");e&&goAjax("/badge/ajax-create-badge",
{title:a,image:b,description:c,shared:d},function(f){modo.badges.showAndSelectAwardBadgeBox(f,$j("#facebox .viewed-user").html())})},saveBadge:function(){var a=$j("#facebox .edit-badge-id").html(),c=$j("#facebox .edit-badge-title").val(),b=$j("#facebox .edit-badge-description").val(),d=$j("#facebox .edit-badge-image-url").html(),e="1";if($j("#facebox .edit-badge-shared-check").attr("checked")==false)e="0";var f=true;if(c==""){f=false;$j("#facebox .edit-badge-title").addClass("error")}else $j("#facebox .edit-badge-title").removeClass("error");
if(d==""){f=false;$j("#facebox .edit-badge-image-wrap").addClass("error")}else $j("#facebox .edit-badge-image-wrap").removeClass("error");f&&goAjax("/badge/ajax-save-badge",{badge_id:a,title:c,image:d,description:b,shared:e},function(){modo.badges.showAndSelectAwardBadgeBox(a,$j("#facebox .viewed-user").html())})},confirmDeleteBadge:function(){$j("#facebox .edit-badge-delete").hide();$j("#facebox .delete-badge-confirm").show()},hideDeleteBadge:function(){$j("#facebox .delete-badge-confirm").hide();
$j("#facebox .edit-badge-delete").show()},deleteBadge:function(){var a=$j("#facebox .edit-badge-id").html();$j("#facebox .delete-badge-yes").hide();$j("#facebox .delete-badge-no").hide();$j("#facebox .delete-badge-loading").show();goAjax("/badge/ajax-delete-badge",{badge_id:a},function(){modo.badges.filterAwardBadgeBox("created_by_me",$j("#facebox .viewed-user").html(),0)})}};
function getInternetExplorerVersion(){var a=-1;if(navigator.appName=="Microsoft Internet Explorer")if(/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)!=null)a=parseFloat(RegExp.$1);return a}function goAjax(a,c,b,d){d=d||"";$j.post(a,c,b,d)}function count(a){var c=0,b;for(b in a)c++;return c}function limit_text(a,c){if(a.value.length>c)a.value=a.value.substring(0,c)}
function trim(a){for(i=0;i<a.length;)if(a.charAt(i)==" "||a.charAt(i)=="\n"||a.charAt(i)=="\t")a=a.substring(i+1,a.length);else break;for(i=a.length-1;i>=0;i=a.length-1)if(a.charAt(i)==" "||a.charAt(i)=="\n"||a.charAt(i)=="\t")a=a.substring(0,i);else break;return a}function addslashes(a){a=a.replace(/\\/g,"\\\\");a=a.replace(/\'/g,"\\'");a=a.replace(/\"/g,'\\"');return a=a.replace(/\0/g,"\\0")}
function stripslashes(a){a=a.replace(/\\'/g,"'");a=a.replace(/\\"/g,'"');a=a.replace(/\\0/g,"\u0000");return a=a.replace(/\\\\/g,"\\")}function inputOnBlur(a,c,b){a=$j(a);if(a.val().replace(/ /g,"")==""){a.val(translated_text[c]);typeof b!="undefined"&&a.css("color",b)}}function inputOnFocus(a,c,b){a=$j(a);if(a.val()==translated_text[c]){a.val("");typeof b!="undefined"&&a.css("color",b)}}function empty(a){return a.replace(/ /g,"")==""}function isset(a,c){return typeof a[c]!="undefined"}
function formatSelectedPage(a,c,b){if(a){a.css("fontWeight","bold");a.css("text-decoration","none")}if(typeof c&&c===true){a.css("position","relative");a.css("top",b)}}function isNumeric(a){var c=true,b;for(i=0;i<a.length&&c==true;i++){b=a.charAt(i);if("0123456789".indexOf(b)==-1)c=false}return c}function defaultImage(a,c){if(c=="avatar")a.src=PATH2_IMAGES+"default-avatars/default_avatar.png";else if(c=="avatar_thumb")a.src=PATH2_IMAGES+"default-avatars/default_avatar_t.png"}
var avatarErrorCount=0;
function onAvatarError(){var a=$j(this).attr("id");if(avatarErrorCount){if(avatarErrorCount==1){$j("#avatar").unbind("error",onAvatarError);$j(".small_avatar").unbind("error",onAvatarError);avatarErrorCount++}$j(this).unbind("error",onAvatarError);a=="avatar"?$j(this).css("float","left").width(140).height(140):$j(this).css("float","left").height(42).width(42)}else{a=="avatar"?$j(this).attr("src",PATH2_IMAGES+"default-avatars/default_avatar.png"):$j(this).attr("src",PATH2_IMAGES+"default-avatars/default_avatar_t.png");
avatarErrorCount++}}$j(document).ready(function(){$j("#avatar, .small_avatar").bind("error",onAvatarError)});function gaTrack(a){_gaq.push(["_trackPageview",a])}function createCookie(a,c,b){var d="";d=new Date;if(typeof b=="undefined")b=365;d.setTime(d.getTime()+b*24*60*60*1E3);d="; expires="+d.toGMTString();document.cookie=a+"="+c+d+"; path=/"}
function readCookie(a){a=a+"=";for(var c=document.cookie.split(";"),b=0;b<c.length;b++){for(var d=c[b];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return d.substring(a.length,d.length)}return null}function substr_count(a,c){var b=a.match(RegExp(c,"g"));return ans=b==null?0:b.length}function strallpos(a,c){for(var b=[],d=a.indexOf(c);d>-1;){b.push(d);d=a.indexOf(c,d+1)}return b}function implode(a,c){var b="",d=count(c)-1,e=0,f;for(f in c){b+=c[f];if(e++<d)b+=a}return b}
function eraseCookie(a){createCookie(a,"",-1)}var replaceProfanities;$j(document).bind("close.facebox",function(){$j("#facebox .content").empty()});
$j(function(){if(!console){console={};console.log=function(){}}var a=[/\sShit\s/ig,/Piss/ig,/Motherfucker/ig,/Fuck/ig,/Cunt/ig,/Cocksucker/ig,/\sTits\s/ig];replaceProfanities=function(c,b){b=b||"*@#$#^#$^*";for(var d in a)c=c.replace(a[d],b);return c};jQuery.superAjax=jQuery.ajax;jQuery.ajax=function(c){!c.no_ga&&AJAX_ANALYTICS&&c.url.indexOf("is-auto-request=true")==-1&&gaTrack(c.url);return jQuery.superAjax(c)}});$j.expr[":"].textEquals=function(a,c,b){return $j(a).text().match("^"+b[3]+"$")};
function addToLibrary(a){a=$j(a);var c=a.parent(),b=c.parent().parent(),d=0;if(b.children(".link-thumb-wrapper").length>0){d=b.children(".link-info");thumb_j=b.children(".link-thumb-wrapper").children(".link_thumb");thumb_j.css("background-image").replace("url(","").replace(")","");d.children(".link_title").html();d.children(".link_url").attr("href");d=c.children(".lib-item-id").val()}else if(c.children(".file-name").length>0){c.children(".file-name").val();d=c.children(".lib-item-id").val()}else if(c.parent().children(".video-url").length>
0){d=c.parent().children("span");d.html();c.parent().children(".video-url").val();d=c.parent().children(".lib-item-id").val()}else if(c.parent().attr("class")=="embed-title"&&c.parent().parent().attr("class")=="links-container"){c.parent().children("span").html();c.children("textarea").val();d=c.children(".lib-item-id").val()}else{b.children(".embed-title-wrapper").children(".embed-title").html()?b.children(".embed-title-wrapper").children(".embed-title").html():b.children(".embed-wrap").children("span").html();
b.children("textarea").val()?b.children("textarea").val():b.children(".embed-wrap").children(".embed-code").html();d=c.children(".lib-item-id").val();b.children(".embed-link-wrapper").children("img").attr("src")&&b.children(".embed-link-wrapper").children("img").attr("src")}goAjax("/library/ajax-add-to-library",{item_id:d});a.html('<img src="/images/icons/book.png"/><span>'+translated_text.added+"</span>");a.addClass("added");b=c.children(".library-score");if(d=b.children("span").html()){c=parseInt(d)+
1;b.children("span").html(c)}else c.append('<span class="library-score"><span>1</span></span>');a.attr("onclick","")}
function getEmbedThumb(a){thumbnail=PATH2_IMAGES+"icons/large/embed.png";if(typeof a.thumb_url!="undefined"&&a.thumb_url!=""&&a.thumb_url!=0&&a.thumb_url!=null)thumbnail=a.thumb_url;else{var c={animoto:"animoto",glogster:"glogster","google-docs":/docs.\*google/,"google-ss":/spreadsheets.\*google/,pixton:"pixton",quizlet:"quizlet",slideshare:"slideshare",youtube:"youtube"};for(provider in c)if(a.embeded_code.match(provider)){thumbnail=PATH2_IMAGES+"icons/embeds/"+provider+".png";if(provider=="youtube")if(a=
a.embeded_code.match(/youtube\.com\/v\/([\w\-]+)/))thumbnail="http://img.youtube.com/vi/"+a[1]+"/default.jpg";break}}return thumbnail}function globalShowCrocoDocViewer(a,c,b,d,e){b=d;if($j(a).attr("croc_uuid"))b=$j(a).attr("croc_uuid");goAjax("/file/get-crocodoc-session",{file:c,uuid:b},function(f){globalDisplayCrocodocViewer(f,e,c,d)})}
function globalDisplayCrocodocViewer(a,c,b,d){a='<iframe width="710" height="500" frameborder="0" src="https://crocodoc.com/view/?sessionId='+eval("("+a+")").sessionId+'"></iframe><p class="crocodoc-new">View document in a <a target="_blank" href="/file/view-crocodoc-new-window?uuid='+d+"&file_id="+b+'">new window</a></p>';$j.facebox(a);$j.facebox.setTitle("File Preview")}
function substr_count2(a,c,b,d){var e=0;a+="";c+="";if(isNaN(b))b=0;if(isNaN(d))d=0;for(b--;(b=a.indexOf(c,b+1))!=-1;)if(d>0&&b+c.length>d)return false;else e++;return e}function test_ipv4(a){return a.match(/(([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/)!=null}
function test_ipv6(a){if(a.length<3)return a=="::";if(a.indexOf(".")>0){lastcolon=a.lastIndexOf(":");if(!(lastcolon&&test_ipv4(a.substr(lastcolon+1))))return false;a=a.substr(0,lastcolon)+":0:0"}if(a.indexOf("::")<0){a=a.match(/^(?:[a-f0-9]{1,4}:){7}[a-f0-9]{1,4}$/i);return a!=null}if(substr_count2(a,":")<8){a=a.match(/^(?::|(?:[a-f0-9]{1,4}:)+):(?:(?:[a-f0-9]{1,4}:)*[a-f0-9]{1,4})?$/i);return a!=null}return false}
function setNewLanguage(a){url=window.location.href;if(url.indexOf("language=")!=-1)url=url.replace(/language=..(-..)*/,"language="+a);else url+=url.indexOf("?")!=-1?"&language="+a:"?language="+a;window.location=url}function chr(a){return String.fromCharCode(a)}
function code2utf(a){if(a<128)return chr(a);if(a<2048)return chr(192+(a>>6))+chr(128+(a&63));if(a<65536)return chr(224+(a>>12))+chr(128+(a>>6&63))+chr(128+(a&63));if(a<2097152)return chr(240+(a>>18))+chr(128+(a>>12&63))+chr(128+(a>>6&63))+chr(128+(a&63))}function _utf8Encode(a){for(var c=[],b=0;b<a.length;b++)c[b]=code2utf(a.charCodeAt(b));return c.join("")}
function utf8Encode(a){for(var c=[],b,d=0,e="";(b=a.search(/[^\x00-\x7F]/))!=-1;){e=a.match(/([^\x00-\x7F]+[\x00-\x7F]{0,10})+/)[0];c[d++]=a.substr(0,b);c[d++]=_utf8Encode(e);a=a.substr(b+e.length)}c[d++]=a;return c.join("")}
function _utf8Decode(a){for(var c=[],b,d,e,f,g=0,h=0;h<a.length;){b=a.charCodeAt(h++);if(b>127)d=a.charCodeAt(h++);if(b>223)e=a.charCodeAt(h++);if(b>239)f=a.charCodeAt(h++);if(b<128)c[g++]=chr(b);else if(b<224)c[g++]=chr((b-192<<6)+(d-128));else if(b<240)c[g++]=chr((b-224<<12)+(d-128<<6)+(e-128));else c[g++]=chr((b-240<<18)+(d-128<<12)+(e-128<<6)+(f-128))}return c.join("")}
function utf8Decode(a){for(var c=[],b=0,d="",e=0;(b=a.search(/[^\x00-\x7F]/))!=-1;){d=a.match(/([^\x00-\x7F]+[\x00-\x7F]{0,10})+/)[0];c[e++]=a.substr(0,b)+_utf8Decode(d);a=a.substr(b+d.length)}c[e++]=a;return c.join("")};
